/**
 * Motionclash
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Image { 
    id?: string;
    imageType?: Image.ImageTypeEnum;
    imagePath?: string;
}
export namespace Image {
    export type ImageTypeEnum = 'ProfilePicture' | 'EventPicture';
    export const ImageTypeEnum = {
        ProfilePicture: 'ProfilePicture' as ImageTypeEnum,
        EventPicture: 'EventPicture' as ImageTypeEnum
    };
}