/**
 * Motionclash
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Image } from './image';
import { UserGroup } from './userGroup';
import { Waypoint } from './waypoint';

export interface Race { 
    id?: string;
    name?: string;
    startDate?: string;
    teams?: Array<UserGroup>;
    eventImages?: Array<Image>;
    waypoints?: Array<Waypoint>;
}